name: iOS Build

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.10.0'
    - name: Install Dependencies
      run: flutter pub get
    - name: Build iOS
      run: flutter build ios --no-codesign
